config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :restaurants, only: [:new, :index, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews 
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  validates :body, presence: true
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant added successfully"
      redirect_to @restaurant
    else
      flash[:notice] = @restaurant.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews 
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      flash[:notice] = "Review added successfully"
      redirect_to @restaurant
    else
      flash[:errors] = @review.errors.full_messages.join(', ')
      render :new
    end
  end

private

  def review_params
    params.require(:review).permit(:rating, :body)

  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
  <%= value %>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<ul>
    <% @restaurants.each do |restaurant| %>
      <li>
        <%=link_to restaurant.name, restaurant_path(restaurant)%>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Add New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant Form</h1>

<%= form_for (@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit 'Add Restaurant'%>

  <%end%>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.address %></h2>
<h3><%= @restaurant.city %></h3>
<h4><%= @restaurant.state %></h4>
<h5><%= @restaurant.zip %></h5>
<h6><%= @restaurant.description %></h6>

<ul>
  <% @reviews.each do |review| %>
    <li>
      <%=review.rating %>
      <%=review.body%>
      <%=review.created_at.strftime("%B %d %Y") %>

    </li>
  <% end %>
  <%= link_to 'Add a Review', new_restaurant_review_path(@restaurant) %>
</ul>

app/views/reviews/new.html.erb
<h1>Review Form for <%= @restaurant.name %></h1>

<%= form_for ([@restaurant, @review]) do |f| %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.label :body, "Review" %>
  <%= f.text_field :body %>

  <%= f.submit 'Add Review'%>

  <%end%>